enum ErrorCode {
  BAD_REQUEST = 'BAD_REQUEST',
  SCHEMA_VALIDATOR = 'SCHEMA_VALIDATOR_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  VIOLETED_TOKEN = 'VIOLETED_TOKEN',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
  UNIQUE_EXCEPTION = 'SQLITE_CONSTRAINT',
}

export default ErrorCode;
